### ISSUE TITLE
Practice 2

### ISSUE THREAD

**Issue by geopimik** [Si1mT/autoware_mini_practice#1]
Please fix the following:
1. When finalizing the node please clean any unnecessary code like debugging [printouts](https://github.com/Si1mT/autoware_mini_practice/blob/main/practice_2/nodes/localization/localizer.py#L50)
2. I would not put the [velocity calculation](https://github.com/Si1mT/autoware_mini_practice/blob/main/practice_2/nodes/localization/localizer.py#L86) in the middle of assigning the values to **current_velocity_msg**. Move it before it or even in the beginning of the callback within other calculations.

Suggestions:
- I would put the [calculations here](https://github.com/Si1mT/autoware_mini_practice/blob/main/practice_2/nodes/localization/localizer.py#L48C9-L48C76) into separate lines. If function returns multiple values, but separating two different calculations with comma is not increasing the readability.

**Comment by Si1mT** [comment]
@geopimik fixed

**Comment by geopimik** [comment]
OK
